### ISSUE TITLE
Adding some default server options

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-mariadb_server#16]
I'm looking to push some of the findings from [here](https://github.com/carlalexander/debops-wordpress/issues/62) upstream. Right now, there's only a `mariadb_server_options` variable to control the server variables. Should we add a new variable like `mariadb_server_default_options` to handle these default options?

**Comment by drybjed** [comment]
Sure, sounds like a good idea. It will be eaiser to add custom, or change the defaults if needed.

**Comment by carlalexander** [comment]
Perfect I'll add that when I add the defaults.

**Comment by carlalexander** [comment]
How would convert this template code to use the two dictionaries?

```jinja
{% if mariadb_server_options|d(False) %}
{% for key, value in mariadb_server_options.iteritems() %}
{% if value is not none %}
{{ "%-23s = %s" | format(key, value) }}
{% else %}
{{ key }}
{% endif %}
{% endfor %}
```

**Comment by drybjed** [comment]
I would go with something like this (not tested):
```
{% if mariadb_server__default_options %}
{%   for key, value in mariadb_server__default_options.iteritems() %}
{%     if key not in mariadb_server__options.keys() %}
{%       if value is not none %}
{{ "%-23s = %s" | format(key, value) }}
{%       else %}
{{ key }}
{%       endif %}
{%     endif %}
{%   endfor %}
{% endif %}
{% if mariadb_server__options %}
{%   for key, value in mariadb_server_options.iteritems() %}
{%     if value is not none %}
{{ "%-23s = %s" | format(key, value) }}
{%     else %}
{{ key }}
{%     endif %}
{%   endfor %}
{% endif %}
```
This way, if user overrides the default options in the normal options, they will take precedence automatically.

**Comment by carlalexander** [comment]
Working on this right now. I did some research and there's a new [`combine`](https://docs.ansible.com/ansible/playbooks_filters.html#combining-hashes-dictionaries) filter in Ansible 2.0 that we can use.
