### ISSUE TITLE
Unable to set charset and collation

### ISSUE THREAD

**Issue by ANPez** [debops/ansible-mariadb_server#17]
On the template file /etc/mysql/conf.d/mysqld.conf there are some hardcoded variables and can't be set by a client.

```
character-set-server    = utf8
collation-server        = utf8_general_ci
init-connect            = 'SET NAMES utf8'
```

**Comment by drybjed** [comment]
Right, I suppose that you might need a different charset than UTF-8. I'll add variables for these in the role. Thanks for the heads up.

**Comment by drybjed** [comment]
This issue should now be solved with new YAML-based configuration structure.

**Comment by drybjed** [comment]
This should be fixed in recent `debops.mariadb_server` releases. Closing.
