### ISSUE TITLE
automysqlupdate package for Ubuntu 14.04 is not compatible with mariadb

### ISSUE THREAD

**Issue by barraponto** [debops/ansible-mariadb_server#2]
I just added the host to the `debops_mariadb_server` and ran `debops`.
I got the following error:
https://gist.github.com/barraponto/d26d1fa3d8fec6bc6ff6/f602179baf0ea1d7de5eec0d8ed5a0f81669b6e2

**Comment by barraponto** [comment]
I tried adding `mysql-client` to the `mariadb_server_packages` variable, but it failed too.
Here's the log: https://gist.github.com/barraponto/d26d1fa3d8fec6bc6ff6

**Comment by barraponto** [comment]
The `automysqlbackup` package for Ubuntu Trusty 14.04 can't be installed together with `mariadb-client`. It was fixed in Debian Jessie and newer versions of Ubuntu (14.10+).

**Comment by barraponto** [comment]
This is being discussed upstream in Ubuntu:
https://bugs.launchpad.net/ubuntu/+source/automysqlbackup/+bug/1483942

**Comment by drybjed** [comment]
So, it looks like Ubuntu team will try and backport the fix to Trusty. In the meantime, you could try switching the mariadb_server_flavor to mysql, it should work fine then. After you test it, it can be added to the flavor map to fix the issue on Trusty for the time being.

**Comment by drybjed** [comment]
It seems that the problem with `automysqlbackup` in Ubuntu Trusty has been fixed, according to the Ubuntu bug database linked above. Due to that, I'm closing this issue.
