### ISSUE TITLE
`mariadb_server__default_options` has been removed?

### ISSUE THREAD

**Issue by ypid** [debops/ansible-mariadb_server#24]
`mariadb_server__default_options` has been removed from defaults/main.yml in 3b85ffa77dc2c53a06625437b6b592dc504f0e08 without a note about this in the CHANGES.rst file. Is this correct?

**Comment by drybjed** [comment]
Yes. My bad, I should have mentioned the explicit variable renames. The contents of the variable have been moved to `mariadb_server__mysqld_performance_options`.

I haven't checked your other PR yet, if you updated the changelog, good, if not, I'll amend the old entry and add the note about rename.

**Comment by ypid** [comment]
I have not yet updated it because I was unsure about it.

**Comment by drybjed** [comment]
This change is already mentioned in the Changelog. Closing.
