### ISSUE TITLE
Issues with the role configuration on Xenial

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-mariadb_server#33]
The `mariadb-server` package on Xenial works a bit differently. There's now two configuration folders: `conf.d` and `mariadb.conf.d`. This new folder contains the file `50-server.cnf` which overwrites most of the configurations in your `mysqld.cnf` in `conf.d`.

The weird thing is that this folder seems to be absent when you use `mariadb_upstream`. Not too sure why there's an inconsistency like that. But the result is that some configuration options like `bind_address` don't work anymore with the default role flavor.

**Comment by drybjed** [comment]
Interesting, always something new to deal with. I'll try to setup a Xenial instance and check it out. Thanks for the heads up.

**Comment by carlalexander** [comment]
The easiest solution might be to just add `xenial` to the `mariadb_server__flavor_map` and make it use `mariadb_upstream`.

**Comment by drybjed** [comment]
Not really - I imagine that Stretch will use a similar approach as well. And by default DebOps roles should use the packages provided by the installed OS if possible, so enabling upstream for a specific release by default isn't a good solution.

**Comment by carlalexander** [comment]
Fair enough 😃

**Comment by drybjed** [comment]
This should be fixed in the latest release of the `debops.mariadb_server` role. Closing.
