### ISSUE TITLE
Role tries to downgrade MariaDB under Ubuntu 14.04 (trusty) on Travis CI

### ISSUE THREAD

**Issue by ypid** [debops/ansible-mariadb_server#41]
Travis Ubuntu 14.04 (trusty) has `mysql-server-5.6` preinstalled but the role wants to switch to `mariadb-server-5.5` which fails with:

```
mysql stop/waiting
Aborting downgrade from (at least) 5.6 to 5.5.
If are sure you want to downgrade to 5.5, remove the file
/var/lib/mysql/debian-*.flag and try installing again.
dpkg: error pro
cessing archive /var/cache/apt/archives/mariadb-server-5.5_5.5.53-1ubuntu0.14.04.1_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while proce
ssing:
 /var/cache/apt/archives/mariadb-server-5.5_5.5.53-1ubuntu0.14.04.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

This is something to note when testing with Ubuntu 14.04 (trusty) on Travis. I guess something like this workaround should be enough: 

Workaround: https://github.com/debops/test-suite/blob/300db87248cd7367b1fcc472502972875f54bb38/ansible-owncloud/test#L29-L30

Bug: https://travis-ci.org/debops/ansible-owncloud/builds/177238085#L1036
Workaround in action: https://travis-ci.org/debops/ansible-owncloud/builds/177238085#L641-L656

**Comment by drybjed** [comment]
Agreed, the same is done with PosgreSQL present on Travis by default.

**Comment by drybjed** [comment]
I have implemented the workaround in the role tests.
