### ISSUE TITLE
Add option to control automysql monthy

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-mariadb_server#47]
Trying to disable all automysqlbackups except the dailies. I noticed there's a `mariadb_server__backup_doweekly` option, but no monthly option. Can I just make a PR that adds a `mariadb_server__backup_domonthly` option and follows the same format?

**Comment by drybjed** [comment]
The `DOWEEKLY` option is implemented in the `automysqlbackup` script, but a monthly alternative is not. Also, this parameter only specifies on what day weekly backups are performed, and doesn't let you enable/disable them. I guess that you could add a separate script executed daily that removes the backups from the weekly and monthly directories.
